basic.pause(100)
basic.showIcon(IconNames.Heart)
music.play(music.stringPlayable("B A G F E D C C ", 200), music.PlaybackMode.UntilDone)
basic.forever(function () {
    pins.digitalWritePin(DigitalPin.P0, 0)
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P2, 0)
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P0, 1)
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P2, 1)
    basic.pause(100)
})
